[profile.default]
src = "contracts/src"
out = "out"
solc_version = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
